# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Piratas - European Pirates | Elecciones europeas del 26 de mayo de 2019
email: hola@piratas.org 
description: >- # this means to ignore newlines until "baseurl:"
  Piratas - European Pirates es una candidatura para las elecciones europeas del próximo
  26 de mayo de 2019, hermandada con los partidos pirata de la Unión Europea.
  
  Democracia directa, transparencia, economía al servicio de las personas, DDHH, Open Access, Open Data, software y cultura libres. ☠
baseurl: "" # the subpath of your site, e.g. /blog
url: "piratas.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: partidos_pirata

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

toc:
  max_level: 2